var BASE_FIREBASE_URL = 'https://mycoffeeapp.firebaseio.com/'
var BASE_FIREBASE_URL_TEST_NODE = 'ws://test.firebaseio.com:5100'
var BASE_FIREBASE_URL_TEST_BROWSER = 'ws://127.0.0.1:5100'

module.exports = {
    BASE_FIREBASE_URL: BASE_FIREBASE_URL
  , BASE_FIREBASE_URL_TEST_NODE: BASE_FIREBASE_URL_TEST_NODE
  , BASE_FIREBASE_URL_TEST_BROWSER: BASE_FIREBASE_URL_TEST_BROWSER
};
